use arc_swap::ArcSwap;
use clipnotex_core::{
    model::{PayloadData, SourceApp},
    settings::ExclusionRule,
};
use std::sync::Arc;

pub struct ExclusionFilter {
    rules: ArcSwap<Vec<ExclusionRule>>,
    respect_concealed: bool,
}

impl ExclusionFilter {
    pub fn new(initial: Vec<ExclusionRule>, respect_concealed: bool) -> Arc<Self> {
        Arc::new(Self {
            rules: ArcSwap::from_pointee(initial),
            respect_concealed,
        })
    }

    pub fn replace_rules(&self, new_rules: Vec<ExclusionRule>) {
        self.rules.store(Arc::new(new_rules));
    }

    pub fn should_block(&self, src: &SourceApp, payloads: &[PayloadData]) -> bool {
        if self.respect_concealed
            && payloads
                .iter()
                .any(|p| is_concealed_format(&p.format_id))
        {
            return true;
        }
        let rules = self.rules.load();
        rules.iter().any(|r| matches_rule(r, src))
    }
}

fn matches_rule(rule: &ExclusionRule, src: &SourceApp) -> bool {
    match rule {
        ExclusionRule::BundleId(id) => src.bundle_id.as_deref() == Some(id.as_str()),
        ExclusionRule::ExeBasename { name, fuzzy } => match &src.exe_basename {
            Some(b) if *fuzzy => b.to_lowercase().starts_with(&name.to_lowercase()),
            Some(b) => b == name,
            None => false,
        },
        ExclusionRule::WindowTitle(pattern) => match &src.window_title {
            Some(t) => glob_match(pattern, t),
            None => false,
        },
    }
}

fn is_concealed_format(format_id: &str) -> bool {
    matches!(
        format_id,
        "org.nspasteboard.ConcealedType"
            | "org.nspasteboard.TransientType"
            | "org.nspasteboard.AutoGeneratedType"
            | "ExcludeClipboardContentFromMonitorProcessing"
    )
}

/// Tiny glob matcher supporting only `*` (any) and `?` (single char).
fn glob_match(pattern: &str, text: &str) -> bool {
    fn helper(p: &[u8], t: &[u8]) -> bool {
        match (p.first(), t.first()) {
            (None, None) => true,
            (Some(b'*'), _) => helper(&p[1..], t) || (!t.is_empty() && helper(p, &t[1..])),
            (Some(b'?'), Some(_)) => helper(&p[1..], &t[1..]),
            (Some(a), Some(b)) if a.eq_ignore_ascii_case(b) => helper(&p[1..], &t[1..]),
            _ => false,
        }
    }
    helper(pattern.as_bytes(), text.as_bytes())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn src_with(bundle: Option<&str>, exe: Option<&str>, title: Option<&str>) -> SourceApp {
        SourceApp {
            bundle_id: bundle.map(String::from),
            exe_basename: exe.map(String::from),
            exe_path: None,
            display_name: String::new(),
            window_title: title.map(String::from),
        }
    }

    #[test]
    fn bundle_match() {
        let f = ExclusionFilter::new(
            vec![ExclusionRule::BundleId("com.x".into())],
            true,
        );
        assert!(f.should_block(&src_with(Some("com.x"), None, None), &[]));
        assert!(!f.should_block(&src_with(Some("com.y"), None, None), &[]));
    }

    #[test]
    fn fuzzy_exe_match() {
        let f = ExclusionFilter::new(
            vec![ExclusionRule::ExeBasename {
                name: "1Password".into(),
                fuzzy: true,
            }],
            true,
        );
        assert!(f.should_block(
            &src_with(None, Some("1Password 8 Helper"), None),
            &[]
        ));
    }

    #[test]
    fn window_title_glob() {
        let f = ExclusionFilter::new(
            vec![ExclusionRule::WindowTitle("*Bitwarden*".into())],
            true,
        );
        assert!(f.should_block(
            &src_with(None, None, Some("Login - Bitwarden")),
            &[]
        ));
    }

    #[test]
    fn concealed_blocks_regardless() {
        let f = ExclusionFilter::new(vec![], true);
        let payloads = vec![PayloadData {
            format_id: "org.nspasteboard.ConcealedType".into(),
            bytes: vec![],
        }];
        assert!(f.should_block(&SourceApp::default(), &payloads));
    }
}
