/* SPDX-License-Identifier: MIT
 * ClipNoteX FFI — C ABI for native frontends.
 * Auto-generated by cbindgen. Do not edit manually.
 */

#ifndef CLIPNOTEX_FFI_H
#define CLIPNOTEX_FFI_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * C callback signature: `fn(hotkey_id: i32, ctx: *mut c_void)`.
 */
typedef void (*CnxCnxHotkeyCallback)(int32_t, void*);

/**
 * C callback signature: `fn(ctx: *mut c_void)` — fired on each clipboard capture.
 */
typedef void (*CnxCnxCaptureCallback)(void*);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Initialize the ClipNoteX core.
 * `data_dir` UTF-8 path. `ephemeral_keys` non-zero means use in-memory keys
 * (dev mode); zero means use OS keychain.
 *
 * Returns 0 on success, negative on error (see `cnx_last_error`).
 */
int32_t cnx_init(const char *data_dir, int32_t ephemeral_keys);

/**
 * Shutdown — currently a no-op (Tokio runtime + state are leaked at exit).
 */
void cnx_shutdown(void);

/**
 * Last error message for the calling thread. Returns null if none.
 * Caller MUST free with [`cnx_free_string`].
 */
char *cnx_last_error(void);

/**
 * Free a string previously returned by ClipNoteX FFI.
 */
void cnx_free_string(char *s);

/**
 * List recent clipboard items.
 * `query` UTF-8 search string or null; `limit` max items (clamped to 200).
 * Returns JSON array; null on error.
 */
char *cnx_list_history_json(const char *query, uintptr_t limit);

/**
 * Paste an item by id.
 * `mode`: 0 = normal, 1 = plain, 2 = format (auto-detect), 3 = full.
 */
int32_t cnx_paste_item(const char *id, int32_t mode);

int32_t cnx_pin_toggle(const char *id);

int32_t cnx_delete_item(const char *id);

int32_t cnx_capture_done(const char *body);

/**
 * `date` is "YYYY-MM-DD" or null (= recent across all dates).
 */
char *cnx_list_done_json(const char *date, uintptr_t limit);

int32_t cnx_delete_done(const char *id);

/**
 * Update a DONE LOG entry's overlay.
 * `args_json` schema:
 *   { "id": "...", "note": "..."|null, "body": "..."|null,
 *     "add_tags": [...], "remove_tags": [...] }
 */
int32_t cnx_update_done_overlay_json(const char *args_json);

char *cnx_export_done_markdown(const char *date);

/**
 * Get current exclusion rules as JSON array.
 * Schema mirrors `ExclusionRule`:
 *   `[{"match":"bundle_id","value":"com.1password.1password"}, ...]`
 */
char *cnx_get_exclusions_json(void);

/**
 * Replace the exclusion rules. Takes effect immediately.
 * `rules_json` must be a JSON array of `ExclusionRule` objects.
 */
int32_t cnx_set_exclusions_json(const char *rules_json);

/**
 * Clear all currently-registered global hotkeys. Use this before calling
 * `cnx_register_hotkey` again with a new accelerator to atomically swap
 * shortcut bindings.
 */
int32_t cnx_clear_hotkeys(void);

/**
 * **DESTRUCTIVE**: wipe all clipboard history + DONE LOG + blob files.
 *
 * Use when encryption state is corrupted (e.g. keychain key changed and
 * old data became permanently undecryptable). The keychain key itself is
 * kept (existing in-memory sealer keeps working for new captures).
 *
 * Returns 0 on success.
 */
int32_t cnx_reset_data(void);

/**
 * Update the history retention cap (max items kept in encrypted store).
 * Returns 0 on success, negative on error.
 * Note: takes effect on the *next* capture; existing items beyond the cap
 * will be evicted in the next QuotaManager pass.
 */
int32_t cnx_set_history_quota(uint64_t max_items);

/**
 * Get current history quota (max items). 0 means "not initialized".
 */
uint64_t cnx_get_history_quota(void);

/**
 * Format text without pasting.
 * `text`     : UTF-8 source.
 * `lang`     : "auto" | "json" | "sql" | "markdown" | "plain" | "html" | ... (or null).
 * `indent`   : spaces for indentation (0 = library default).
 *
 * Returns JSON `{ formatted: "...", detected_lang: "..." }`; null on error.
 */
char *cnx_format_preview_json(const char *text, const char *lang, uint32_t indent);

/**
 * Register a hotkey. `accelerator` is e.g. "Cmd+Shift+V".
 */
int32_t cnx_register_hotkey(int32_t id, const char *accelerator);

/**
 * Drain pending hotkey OS events. Call this from the main thread runloop
 * (Swift: `Timer.scheduledTimer(withTimeInterval: 0.05, ...)` or a CFRunLoop source).
 */
void cnx_hotkey_pump(void);

void cnx_set_hotkey_callback(CnxCnxHotkeyCallback cb, void *ctx);

void cnx_set_capture_callback(CnxCnxCaptureCallback cb, void *ctx);

int32_t cnx_start_capture_loop(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CLIPNOTEX_FFI_H */
