//! macOS clipboard backend — real NSPasteboard implementation (M3-mac).
//!
//! Design decisions:
//! 1. Single-snapshot model (concern §3 / DESIGN §5.1)
//!    changeCount を確認 → `pasteboardItems` を 1 回だけ取得 →
//!    同じスナップショットに対して全 `dataForType:` を順次呼ぶ。
//!    スナップショット後に changeCount が進んだら RaceRetry を返す。
//!
//! 2. All data reads are in `spawn_blocking` (concern §3 / DESIGN §10.1)
//!    `dataForType:` は遅延生成でブロックする可能性があるため
//!    Tokio のスレッドプールに逃がし、async executor をブロックしない。
//!
//! 3. Self-write guard (concern §1 / DESIGN §5.4)
//!    自分の書込 digest を LRU で保持し、write 直前に register して
//!    changeCount 変化時に無視する。
//!
//! 4. Concealed types (DESIGN §4.2)
//!    ConcealedType / TransientType / AutoGeneratedType があれば全体を破棄。
//!
//! 5. org.nspasteboard.source (DESIGN §4.2)
//!    書いたアプリが source を埋めていればそれを bundle_id として優先。

use crate::guard::SelfWriteGuard;
use crate::platform::{CapturedItem, ClipboardWatcher, ClipboardWriter};
use crate::safelist::{is_mac_concealed, is_mac_safe};
use async_trait::async_trait;
use clipnotex_core::{
    model::{ClipKind, PayloadData, SourceApp},
    CnxError, Result,
};
use objc2::rc::Retained;
use objc2::runtime::ProtocolObject;
use objc2_app_kit::{NSPasteboard, NSPasteboardItem, NSPasteboardWriting, NSWorkspace};
use objc2_foundation::{NSArray, NSData, NSString};
use std::sync::Arc;
use std::sync::atomic::{AtomicI64, Ordering};
use std::time::Duration;

const POLL_INTERVAL_MS: u64 = 100;
#[allow(dead_code)]
const MAX_RACE_RETRIES: u32 = 3;

// ---------------------------------------------------------------------------
// Watcher
// ---------------------------------------------------------------------------

pub struct MacWatcher {
    guard: Arc<SelfWriteGuard>,
    poll: Duration,
    last_change_count: AtomicI64,
}

impl MacWatcher {
    pub fn new(guard: Arc<SelfWriteGuard>) -> Result<Self> {
        Ok(Self {
            guard,
            poll: Duration::from_millis(POLL_INTERVAL_MS),
            last_change_count: AtomicI64::new(i64::MIN),
        })
    }
}

#[async_trait]
impl ClipboardWatcher for MacWatcher {
    async fn next(&mut self) -> Result<Option<CapturedItem>> {
        loop {
            tokio::time::sleep(self.poll).await;

            // Fast poll: skip if changeCount hasn't moved.
            let cc = pasteboard_change_count();
            let prev = self.last_change_count.load(Ordering::Acquire);
            if cc == prev {
                continue;
            }
            self.last_change_count.store(cc, Ordering::Release);

            let guard = self.guard.clone();
            let result = tokio::task::spawn_blocking(move || read_snapshot(cc, &guard))
                .await
                .map_err(|e| CnxError::Clipboard(format!("spawn_blocking join: {e}")))?;

            match result {
                ReadResult::Captured(item) => return Ok(Some(item)),
                ReadResult::RaceRetry => {
                    // Advance baseline to the latest count and try again.
                    self.last_change_count
                        .store(pasteboard_change_count(), Ordering::Release);
                }
                ReadResult::Skip(reason) => {
                    tracing::debug!("clipboard skip: {reason}");
                }
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Blocking read (runs inside spawn_blocking)
// ---------------------------------------------------------------------------

enum ReadResult {
    Captured(CapturedItem),
    RaceRetry,
    Skip(String),
}

fn read_snapshot(expected_cc: i64, guard: &SelfWriteGuard) -> ReadResult {
    // SAFETY: NSPasteboard is thread-safe for read operations.
    // All calls happen on the same blocking thread; no Retained value crosses
    // threads because we extract raw bytes immediately.
    let (all_types, primary_bytes) = unsafe {
        let pb = NSPasteboard::generalPasteboard();
        let items: Retained<NSArray<NSPasteboardItem>> = match pb.pasteboardItems() {
            Some(i) => i,
            None => return ReadResult::Skip("no pasteboard items".into()),
        };
        let first: &NSPasteboardItem = match items.first() {
            Some(i) => i,
            None => return ReadResult::Skip("empty pasteboard".into()),
        };

        // NSPasteboardItem::types() returns Retained<NSArray<NSPasteboardType>>
        // where NSPasteboardType = NSString. Use get() for bounds-checked access.
        let type_arr = first.types();
        let types: Vec<String> = (0..type_arr.len())
            .filter_map(|i| type_arr.get(i).map(|s| s.to_string()))
            .collect();

        if types.is_empty() {
            return ReadResult::Skip("no types on item".into());
        }

        // Concealed-type guard (DESIGN §4.2).
        if types.iter().any(|t| is_mac_concealed(t)) {
            return ReadResult::Skip("concealed type".into());
        }

        // Read the primary type for the self-write digest.
        let primary_uti = types
            .iter()
            .find(|t| t.as_str() == "public.utf8-plain-text")
            .or_else(|| types.first())
            .cloned()
            .unwrap_or_default();

        let primary_bytes = read_item_data(first, &primary_uti);
        (types, primary_bytes)
    };

    if primary_bytes.is_empty() {
        return ReadResult::Skip("primary payload empty".into());
    }

    // Self-write guard.
    let digest: [u8; 32] = blake3::hash(&primary_bytes).into();
    if guard.contains(&digest) {
        return ReadResult::Skip("self-write".into());
    }

    // Read all safe-listed types from the *same* snapshot.
    let payloads: Vec<PayloadData> = all_types
        .iter()
        .filter(|t| is_mac_safe(t))
        .map(|uti| {
            // SAFETY: same blocking thread, same NSPasteboardItem snapshot.
            let bytes = unsafe {
                let pb = NSPasteboard::generalPasteboard();
                match pb.pasteboardItems().and_then(|arr| arr.first_retained()) {
                    Some(item) => read_item_data(&item, uti),
                    None => vec![],
                }
            };
            PayloadData {
                format_id: uti.clone(),
                bytes,
            }
        })
        .collect();

    // changeCount race check: re-read AFTER all dataForType: calls.
    let cc_after = pasteboard_change_count();
    if cc_after != expected_cc {
        tracing::warn!(
            "changeCount changed during read ({expected_cc}→{cc_after}), discarding"
        );
        return ReadResult::RaceRetry;
    }

    let source_app = detect_source_blocking(&all_types);
    let primary_kind = kind_from_types(&all_types);
    let captured_at = chrono::Utc::now().timestamp_millis();

    ReadResult::Captured(CapturedItem {
        source_app,
        payloads,
        primary_kind,
        digest,
        captured_at,
    })
}

/// Read bytes for a single UTI from a pasteboard item.
///
/// # Safety
/// Must be called on a thread where Objective-C message sending is safe.
/// `item` must remain valid for the duration of this call.
unsafe fn read_item_data(item: &NSPasteboardItem, uti: &str) -> Vec<u8> {
    let ns_type = NSString::from_str(uti);
    match item.dataForType(&ns_type) {
        Some(data) => data.bytes().to_vec(),
        // nil → promised type not yet delivered; record empty (DESIGN §5.1 note 5).
        None => {
            tracing::trace!("promised/nil data for UTI: {uti}");
            vec![]
        }
    }
}

fn pasteboard_change_count() -> i64 {
    // SAFETY: NSPasteboard.generalPasteboard() and changeCount are safe to
    // call from any thread.
    unsafe { NSPasteboard::generalPasteboard().changeCount() as i64 }
}

fn kind_from_types(types: &[String]) -> ClipKind {
    for t in types {
        match t.as_str() {
            "public.png" | "public.jpeg" | "public.tiff" | "public.heic" => {
                return ClipKind::Image
            }
            "public.rtf" => return ClipKind::Rtf,
            "public.html" => return ClipKind::Html,
            "com.adobe.pdf" => return ClipKind::Pdf,
            "public.file-url" => return ClipKind::Files,
            "public.utf8-plain-text" | "public.utf16-plain-text" => return ClipKind::Text,
            _ => {}
        }
    }
    ClipKind::Custom
}

// ---------------------------------------------------------------------------
// Source detection
// ---------------------------------------------------------------------------

/// Detect the app that wrote to the clipboard.
///
/// Priority (DESIGN §4.2):
///  1. `org.nspasteboard.source` — written by the source app itself.
///  2. `NSWorkspace.frontmostApplication`.
///
/// Called from the blocking read task; NSWorkspace queries are safe off-main.
fn detect_source_blocking(types: &[String]) -> SourceApp {
    detect_source().unwrap_or_else(|| detect_source_from_pasteboard_types(types))
}

/// Read `org.nspasteboard.source` if present.
fn detect_source_from_pasteboard_types(types: &[String]) -> SourceApp {
    if types.contains(&"org.nspasteboard.source".to_string()) {
        if let Some(src) = read_nspasteboard_source() {
            return src;
        }
    }
    detect_frontmost().unwrap_or_default()
}

fn read_nspasteboard_source() -> Option<SourceApp> {
    // SAFETY: pasteboard read, blocking thread.
    unsafe {
        let pb = NSPasteboard::generalPasteboard();
        let items = pb.pasteboardItems()?;
        let first = items.first()?;
        let key = NSString::from_str("org.nspasteboard.source");
        let data = first.dataForType(&key)?;
        // The source bundle identifier is stored as a UTF-8 string.
        let bundle_id = String::from_utf8(data.bytes().to_vec()).ok()?;
        Some(SourceApp {
            bundle_id: Some(bundle_id.clone()),
            display_name: bundle_id,
            ..Default::default()
        })
    }
}

fn detect_frontmost() -> Option<SourceApp> {
    // SAFETY: NSWorkspace.sharedWorkspace and frontmostApplication are safe.
    unsafe {
        let ws = NSWorkspace::sharedWorkspace();
        let app = ws.frontmostApplication()?;
        let bundle_id = app.bundleIdentifier().map(|s| s.to_string());
        let display_name = app
            .localizedName()
            .map(|s| s.to_string())
            .unwrap_or_default();
        Some(SourceApp {
            bundle_id,
            display_name,
            ..Default::default()
        })
    }
}

pub fn detect_source() -> Option<SourceApp> {
    detect_frontmost()
}

// ---------------------------------------------------------------------------
// Writer
// ---------------------------------------------------------------------------

pub struct MacWriter;

impl MacWriter {
    pub fn new() -> Result<Self> {
        Ok(Self)
    }
}

impl ClipboardWriter for MacWriter {
    fn write(&self, payloads: &[PayloadData]) -> Result<()> {
        // SAFETY: NSPasteboard writes should happen on the main thread or in a
        // context where NSApplication has been initialized. Tauri ensures this.
        unsafe {
            let pb = NSPasteboard::generalPasteboard();
            pb.clearContents();

            // Build one NSPasteboardItem containing all formats.
            let item = NSPasteboardItem::new();
            for p in payloads {
                if p.bytes.is_empty() {
                    continue;
                }
                let uti = NSString::from_str(&p.format_id);
                let data = NSData::with_bytes(&p.bytes);
                // setData:forType: returns YES on success; log failures.
                if !item.setData_forType(&data, &uti) {
                    tracing::warn!("NSPasteboardItem setData failed for UTI: {}", p.format_id);
                }
            }
            // writeObjects: takes NSArray<ProtocolObject<dyn NSPasteboardWriting>>.
            // NSPasteboardItem conforms to NSPasteboardWriting via ImplementedBy.
            let writing: Retained<ProtocolObject<dyn NSPasteboardWriting>> =
                ProtocolObject::from_retained(item);
            let items = NSArray::from_vec(vec![writing]);
            if !pb.writeObjects(&items) {
                return Err(CnxError::Clipboard(
                    "NSPasteboard.writeObjects returned NO".into(),
                ));
            }
        }
        Ok(())
    }

    fn snapshot_for_restore(&self) -> Result<Vec<PayloadData>> {
        // SAFETY: blocking read, same rules as read_snapshot.
        let payloads: Vec<PayloadData> = unsafe {
            let pb = NSPasteboard::generalPasteboard();
            let items = match pb.pasteboardItems() {
                Some(i) => i,
                None => return Ok(vec![]),
            };
            let first = match items.first() {
                Some(i) => i,
                None => return Ok(vec![]),
            };
            let type_arr = first.types();
            let types: Vec<String> = (0..type_arr.len())
                .filter_map(|i| type_arr.get(i).map(|s| s.to_string()))
                .collect();
            types
                .iter()
                .filter(|t| is_mac_safe(t))
                .map(|uti| {
                    let bytes = read_item_data(first, uti);
                    PayloadData {
                        format_id: uti.clone(),
                        bytes,
                    }
                })
                .collect()
        };
        Ok(payloads)
    }
}
