//! Whitelist of clipboard formats we know how to safely consume.
//!
//! See DESIGN.md §5.2 — naively reading every CF_* format on Windows is
//! a fast path to UB. Likewise, on macOS some UTI types contain promised
//! data that may not be retrievable without crashes when the source app
//! has gone away.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FormatHandler {
    SafeText,
    DibToPng,
    BitmapToPng,
    TiffToPng,
    FilePathsOnly,
    /// Format name is recorded but data is not retrieved in v0.1.
    Unknown,
}

/// macOS: types we always read.
pub const MAC_SAFE_TYPES: &[&str] = &[
    "public.utf8-plain-text",
    "public.utf16-plain-text",
    "public.rtf",
    "public.html",
    "public.png",
    "public.jpeg",
    "public.tiff",
    "com.adobe.pdf",
    "public.file-url",
];

/// macOS: presence of any of these means "do not capture".
pub const MAC_CONCEALED_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
];

pub fn is_mac_safe(uti: &str) -> bool {
    MAC_SAFE_TYPES.contains(&uti)
}

pub fn is_mac_concealed(uti: &str) -> bool {
    MAC_CONCEALED_TYPES.contains(&uti)
}

/// Windows standard CF_* values we care about. Registered formats are
/// matched by name (see `classify_windows`).
pub mod win_cf {
    pub const CF_TEXT: u32 = 1;
    pub const CF_BITMAP: u32 = 2;
    pub const CF_OEMTEXT: u32 = 7;
    pub const CF_DIB: u32 = 8;
    pub const CF_UNICODETEXT: u32 = 13;
    pub const CF_TIFF: u32 = 6;
    pub const CF_HDROP: u32 = 15;
    pub const CF_DIBV5: u32 = 17;
}

pub fn classify_windows(format: u32, registered_name: Option<&str>) -> FormatHandler {
    use win_cf::*;
    match format {
        CF_UNICODETEXT | CF_TEXT | CF_OEMTEXT => FormatHandler::SafeText,
        CF_DIB | CF_DIBV5 => FormatHandler::DibToPng,
        CF_BITMAP => FormatHandler::BitmapToPng,
        CF_TIFF => FormatHandler::TiffToPng,
        CF_HDROP => FormatHandler::FilePathsOnly,
        _ => match registered_name {
            Some("HTML Format") | Some("Rich Text Format") => FormatHandler::SafeText,
            Some("FileGroupDescriptorW") | Some("FileNameW") => FormatHandler::SafeText,
            _ => FormatHandler::Unknown,
        },
    }
}

/// Names of registered Windows clipboard formats that, if present, mean
/// "do not capture" (DESIGN §4.2).
pub const WIN_EXCLUDE_FORMATS: &[&str] = &[
    "ExcludeClipboardContentFromMonitorProcessing",
    "CanIncludeInClipboardHistory", // value "0" from owner — handled by reader
];
